"""update document model

Revision ID: 0f02ec55a9ed
Revises: 65d7c3a62816
Create Date: 2026-08-05 12:59:50.080473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f02ec55a9ed'
down_revision: Union[str, Sequence[str], None] = '65d7c3a62816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('filename', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('content_type', sa.String(length=100), nullable=False))
    op.add_column('documents', sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('documents', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('documents_stored_filename_key'), 'documents', type_='unique')
    op.drop_column('documents', 'stored_filename')
    op.drop_column('documents', 'original_filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('stored_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('documents_stored_filename_key'), 'documents', ['stored_filename'], postgresql_nulls_not_distinct=False)
    op.alter_column('documents', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('documents', 'uploaded_at')
    op.drop_column('documents', 'content_type')
    op.drop_column('documents', 'filename')
    # ### end Alembic commands ###
