"""change embedding dimension to 384

Revision ID: 129dbabe4327
Revises: 4403bb36f63b
Create Date: 2026-08-13 08:32:50.185294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '129dbabe4327'
down_revision: Union[str, Sequence[str], None] = '4403bb36f63b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunks', 'embedding',
                existing_type=Vector(1536),
                type_=Vector(384),
                existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunks', 'embedding',
                existing_type=Vector(1536),
                type_=Vector(384),
                existing_nullable=True)
    # ### end Alembic commands ###
